
from framework.domain.abstract_domain_config import AbstractDomainConfig
from framework.domain.shape_definer import ShapeDefiner


class NetworkDomainConfig(AbstractDomainConfig, ShapeDefiner):
    """
    Abstract class whose domain-specific implementations reflect a domain's
    chance to tell the system about different aspects of data-driven
    configuration.

    A 'NetworkDomainConfig' instance for ENN describes the data that's required
    for training and evaluation, including where it is, and how to load it
    and use it.

    Also, a chance is afforded by this class to translate some domain-specific
    parameters into parameters that the service-side NetworkBuilder would
    need to know.

    Each instance is intended to be stateless, and thus no constructor
    is necessary.
    """


    def generate_default_info_dict(self, extra_config):
        """
        Generates the default values for the domain-specific configuration
        dictionary.

        :param extra_config: A first stab at a domin-specific configuration
            dictionary, as read-in by build_config().  This will include all
            domain-specific configuration read in, including potentially
            misspelled keys (this class doesn't know what is valid yet at this
            point). This allows for the defaults generated by the method to
            depend on other values, if that is necessary.

        :return: A dictionary of *default* domain-specific configuration, whose
            values will be mixed with what was read in from the config files
            inside the build_config() method.

            Dictionary structure can be whatever you like, because it is only
            domain evaluation code that will be reading this data. Nested
            structures, lists and primitives are OK, however any scalar
            leaf-node data must be simple primitives (like strings, floats,
            ints, booleans) that are easily JSON-able. Specifically: code
            objects are not allowed, as this information goes over the wire
            to the workers.

            By default, this generic implementation returns an empty dictionary
            with no defaults, as we dont'know anything about the domain-
            specifics at this level.
        """
        return {}


    def generate_filename_dict(self, domain_specific_dict):
        """
        :param domain_specific_dict: The assembled domain-specific configuration
            dictionary, with defaults and read-in values already mixed together.

        :return: A dictionary of domain-specific file configuration information,
            where keys are logical references to data files and values are
            data files whose contents need to make it over to each worker.

            By default, this generic implementation returns an empty dictionary
            with no defaults, as we dont'know anything about the domain-
            specifics at this level.
        """
        return {}


    def determine_num_tasks(self, domain_specific_dict):
        """
        Called by the SessionServer.

        :param domain_specific_dict: The assembled domain-specific configuration
            dictionary, with defaults and read-in values already mixed together.
        :return: An integer representing the number of tasks for the network.
            By default a value of "None" is returned, indicating that the
            value is indicated in the network builder configuration
            directly, or is determined by that config's defaults.

        This method translates some domain-specific configuration information
        into generalized specifications for the inputs and outputs of the
        network.  The information created here gets sent to the service
        to be digested by the network constructor.

        While it is conceivable that what gets specified here could be done
        statically in the builder config file, that, however, can be a bit
        cumbersome, and the programmatic interpretation of a few domain config
        parameters tends to have fewer errors.
        """
        return None


    def determine_input_shapes(self, domain_specific_dict):
        """
        Called by the SessionServer.

        :param domain_specific_dict: The assembled domain-specific configuration
            dictionary, with defaults and read-in values already mixed together.
        :return: A list representing the input shape specifications.
            By default a value of "None" is returned, indicating that the
            value is indicated in the network builder configuration
            directly, or is determined by that config's defaults.

        The input and/or output shapes specification can each take one of
        a few forms:

                1.  A single list that describes a single shape
                    for a single terminal to be used for all tasks.
                    Like this:  [ 128, 128, 1 ]

                2.  A list of lists that describes a different shape
                    for each single-terminal task. Length of the outer
                    list must equal 'num_tasks' in the config for this
                    to be valid. Like this for num_tasks = 3:
                        [ [ 56, 56, 1 ], [ 23, 23, 1 ], [ 4096, 1 ] ]

                    Note that semantically, this *could* describe a
                    common multi-terminal spec for each task when all
                    tasks terminals are the same. Unfortunately this
                    case is indistinguishable from the case described
                    above and any multi-terminal task must use a fully-
                    specified list described in method (3) below,
                    repeats or no.

                3.  A list of lists of lists that describes a different
                    shape for each terminal of a multi-terminal task.
                    Length of the outer list must equal 'num_tasks' in
                    the config for this to be valid.

                    The outer-most list has one entry per task.
                    The middle-most list has one entry per task-terminal,
                    even if any given task only has a single terminal.
                    The inner-most list has one entry per shape dimension
                    for the task-terminal.

                    Like this:  (1st task - 1 terminal,
                                 2nd task - 2 terminals,
                                 3rd task - 3 terminals)
                        [   [ [ 4096, 1 ] ],
                            [ [ 56, 56, 1 ], [ 23, 23, 1 ] ],
                            [ [ 256, 256, 1 ], [ 56, 56, 1 ], [ 18, 1 ] ]
                        ]

        This method translates some domain-specific configuration information
        into generalized specifications for the inputs and outputs of the
        network.  The information created here gets sent to the service
        to be digested by the network constructor.

        While it is conceivable that what gets specified here could be done
        statically in the builder config file, that, however, can be a bit
        cumbersome, and the programmatic interpretation of a few domain config
        parameters tends to have fewer errors.
        """
        return None


    def determine_output_shapes(self, domain_specific_dict):
        """
        Called by the SessionServer.

        :param domain_specific_dict: The assembled domain-specific configuration
            dictionary, with defaults and read-in values already mixed together.
        :return: A list representing the output shape specifications.
            By default a value of "None" is returned, indicating that the
            value is indicated in the network builder configuration
            directly, or is determined by that config's defaults.

        The input and/or output shapes specification can each take one of
        a few forms:

                1.  A single list that describes a single shape
                    for a single terminal to be used for all tasks.
                    Like this:  [ 128, 128, 1 ]

                2.  A list of lists that describes a different shape
                    for each single-terminal task. Length of the outer
                    list must equal 'num_tasks' in the config for this
                    to be valid. Like this for num_tasks = 3:
                        [ [ 56, 56, 1 ], [ 23, 23, 1 ], [ 4096, 1 ] ]

                    Note that semantically, this *could* describe a
                    common multi-terminal spec for each task when all
                    tasks terminals are the same. Unfortunately this
                    case is indistinguishable from the case described
                    above and any multi-terminal task must use a fully-
                    specified list described in method (3) below,
                    repeats or no.

                3.  A list of lists of lists that describes a different
                    shape for each terminal of a multi-terminal task.
                    Length of the outer list must equal 'num_tasks' in
                    the config for this to be valid.

                    The outer-most list has one entry per task.
                    The middle-most list has one entry per task-terminal,
                    even if any given task only has a single terminal.
                    The inner-most list has one entry per shape dimension
                    for the task-terminal.

                    Like this:  (1st task - 1 terminal,
                                 2nd task - 2 terminals,
                                 3rd task - 3 terminals)
                        [   [ [ 4096, 1 ] ],
                            [ [ 56, 56, 1 ], [ 23, 23, 1 ] ],
                            [ [ 256, 256, 1 ], [ 56, 56, 1 ], [ 18, 1 ] ]
                        ]

        This method translates some domain-specific configuration information
        into generalized specifications for the inputs and outputs of the
        network.  The information created here gets sent to the service
        to be digested by the network constructor.

        While it is conceivable that what gets specified here could be done
        statically in the builder config file, that, however, can be a bit
        cumbersome, and the programmatic interpretation of a few domain config
        parameters tends to have fewer errors.
        """
        return None


    def get_default_evaluation_common_config(self):
        """
        Prepares a default dictionary for evaluation configuration
        that is used by the common evaluation code on the worker
        (i.e. what is in framework.client_script.client.py)
        """

        network_default_config = {

            # We assume that there are three datasets: train, val, test.
            'train_dataset': "train",

            # The data set to use for validation.
            'test_dataset': "test",

            # Whether to reduce the size of the training data
            'subsample': False,
            # The number of samples to keep if subsample is set to true
            'subsample_amount': None,

            # Whether to reduce the size of the test data
            'test_subsample': False,
            # The number of test samples to keep if test_subsample is set to
            # true
            'test_subsample_amount': None,

            'num_iterations_per_epoch': 500,

            'upload_best_model': False,
            'upload_trained_model': False,
            'custom_train_seed': None,
            'test_val_only': True,

            'test_every_epoch': True,
            'checkpoint_dir': ".",
            'timestamp_chkpt_dir': False,
            'load_checkpoint': False,
            'num_epochs': 10,
            'batch_size': 1,
            'checkpoint_interval': None,
            'persist_weights': False,

            'shuffle_data': False,
            'train_abs_num_epochs': False
        }

        default_config = super(NetworkDomainConfig,
                               self).get_default_evaluation_common_config()

        default_config.update(network_default_config)

        return default_config


    def generate_builder_config_add_ons(self, domain_config):
        """
        :param domain_config: Domain-specific configuration dictionary.
        :return: a dictionary that will be used to update() the builder
                config dictionary sent to the service
        """
        builder_add_ons = {}

        # Pylint cannot seem to tell that these methods we call here
        # might be overridden by a subclass.
        # pylint: disable=assignment-from-none
        num_tasks = self.determine_num_tasks(domain_config)
        if num_tasks is not None:
            builder_add_ons['num_tasks'] = num_tasks

        input_shapes = self.determine_input_shapes(domain_config)
        if input_shapes is not None:
            builder_add_ons['input_shapes'] = input_shapes

        output_shapes = self.determine_output_shapes(domain_config)
        if output_shapes is not None:
            builder_add_ons['output_shapes'] = output_shapes

        return builder_add_ons
