
import copy
from framework.domain.network_domain_config import NetworkDomainConfig

from domain.omniglot.random_alphabet_ordering import get_random_alphabet_ordering

# Override for number of tasks
ALPHABET_INFO = {
    "Inuktitut-(Canadian-Aboriginal-Syllabics)": 16,
    "Alphabet-of-the-Magi": 20,
    "Cyrillic": 33,
    "Ge-ez": 26,
    "Oriya": 46,
    "Avesta": 26,
    "Gujarati": 48,
    "Blackfoot-(Canadian-Aboriginal-Syllabics)": 14,
    "Asomtavruli-(Georgian)": 40,
    "Old-Church-Slavonic-(Cyrillic)": 45,
    "Sanskrit": 42,
    "Korean": 40,
    "Japanese-(katakana)": 47,
    "Syriac-(Serto)": 23,
    "Balinese": 24,
    "Atemayar-Qelisayer": 26,
    "Latin": 26,
    "Mkhedruli-(Georgian)": 41,
    "Burmese-(Myanmar)": 34,
    "Sylheti": 28,
    "Grantha": 43,
    "Ojibwe-(Canadian-Aboriginal-Syllabics)": 14,
    "Tengwar": 25,
    "Bengali": 46,
    "Tibetan": 42,
    "Armenian": 41,
    "ULOG": 26,
    "Japanese-(hiragana)": 52,
    "Tifinagh": 55,
    "Glagolitic": 45,
    "Braille": 26,
    "Hebrew": 22,
    "Greek": 24,
    "Keble": 26,
    "Early-Aramaic": 22,
    "Gurmukhi": 45,
    "Malayalam": 47,
    "Malay-(Jawi---Arabic)": 40,
    "Angelic": 20,
    "Aurek-Besh": 26,
    "Arcadian": 26,
    "Kannada": 41,
    "Anglo-Saxon-Futhorc": 29,
    "N-Ko": 33,
    "Futurama": 26,
    "Mongolian": 30,
    "Syriac-(Estrangelo)": 23,
    "Manipuri": 40,
    "Atlantean": 26,
    "Tagalog": 17
}


class OmniglotDomainConfig(NetworkDomainConfig):
    """
    Implementation of the DomainConfig class for the omniglot domain, the
    domain's chance to tell the system about different aspects of data-driven
    configuration.

    A 'DomainConfig' instance for ENN describes the data that's required
    for training and evaluation, including where it is, and how to load it
    and use it.

    Also, a chance is afforded by this class to translate some domain-specific
    parameters into parameters that the service-side NetworkBuilder would
    need to know.

    Each instance is intended to be stateless, and thus no constructor
    is necessary.
    """


    def generate_default_info_dict(self, extra_config):
        """
        Generates the default values for the domain-specific configuration
        dictionary.

        :param extra_config: A first stab at a domin-specific configuration
            dictionary, as read-in by build_config().  This will include all
            domain-specific configuration read in, including potentially
            misspelled keys (this class doesn't know what is valid yet at this
            point). This allows for the defaults generated by the method to
            depend on other values, if that is necessary.

        :return: A dictionary of *default* domain-specific configuration, whose
            values will be mixed with what was read in from the config files
            inside the build_config() method.

            Dictionary structure can be whatever you like, because it is only
            domain evaluation code that will be reading this data. Nested
            structures, lists and primitives are OK, however any scalar
            leaf-node data must be simple primitives (like strings, floats,
            ints, booleans) that are easily JSON-able. Specifically: code
            objects are not allowed, as this information goes over the wire
            to the workers.
        """

        # Load the constants for the domain and have that data be
        # referenceable via the info dictionary.
        alphabet_size_dict = copy.deepcopy(ALPHABET_INFO)
        alphabet_sizes = [(a.replace("_", "-"), \
                           alphabet_size_dict[a.replace("_", "-")]) for a in \
                          get_random_alphabet_ordering()]

        # Get the extra config that was read in from the domain config
        # dictionary.  # "Extra" here means any key that was not understood by
        # the DomainConfig superclass.
        num_tasks = extra_config.get('num_tasks', len(alphabet_sizes))

        default_info = {

            #
            # Parameters that get fed into the parameters network constructor
            # Some of these might also get used in evaluation.
            #

            # Assuming square images
            'image_size': 105,
            'num_tasks': num_tasks,

            'task_names': [x[0] for x in alphabet_sizes][:num_tasks],
            'alphabet_sizes': [x[1] for x in alphabet_sizes][:num_tasks],

            #
            # Parameters for evaluation
            #

            # When true, a smaller data set is used for quick tests.
            'use_test_data': False,

            # When true, augment turns on an image augmentation path in the
            # evaluator
            'augment': False,
            'crop_amount': 16,

            # Parameters for using the evolved learning rate (lr)
            # XXX It could be that these are not used any more, with newer
            #     code favoring the evolved global hyperparameters.
            'lr_scale': 1.0,
            'lr_floor': 0.0,
            'lr_decay': 10,
            'lr_decay_amount': 0.1
        }

        return default_info


    def generate_filename_dict(self, domain_specific_dict):
        """
        Generates filenames of required data files, these names are used to
        determine s3 address for download as well as local basedir and
        enn_cache file paths.  They are also the names of the folders inside
        the any archive (tar.gz) files

        :param domain_specific_dict: The assembled domain-specific configuration
            dictionary, with defaults and read-in values already mixed together.

        :return: A dictionary of domain-specific file configuration information,
            where keys are logical references to data files and values are
            data files whose contents need to make it over to each worker.
        """

        use_test_data = domain_specific_dict.get("use_test_data", False)

        if use_test_data:
            # This file is a lot shorter than the full data
            # and is useful for short-running tests.
            filename_dict = {
                "omniglot2.tar.gz" : "omniglot2.tar.gz"
            }
        else:
            filename_dict = {
                'datafile': "omniglot2.bin"
            }
        return filename_dict


    def determine_num_tasks(self, domain_specific_dict):
        """
        Called by the SessionServer.

        :param domain_specific_dict: The assembled domain-specific configuration
            dictionary, with defaults and read-in values already mixed together.
        :return: An integer representing the number of tasks for the network.
            By default a value of "None" is returned, indicating that the
            value is indicated in the network builder configuration
            directly, or is determined by that config's defaults.

        This method translates some domain-specific configuration information
        into generalized specifications for the inputs and outputs of the
        network.  The information created here gets sent to the service
        to be digested by the network constructor.

        While it is conceivable that what gets specified here could be done
        statically in the builder config file, that, however, can be a bit
        cumbersome, and the programmatic interpretation of a few domain config
        parameters tends to have fewer errors.
        """
        num_tasks = domain_specific_dict['num_tasks']
        return num_tasks


    def determine_input_shapes(self, domain_specific_dict):
        """
        Called by the SessionServer.

        :param domain_specific_dict: The assembled domain-specific configuration
            dictionary, with defaults and read-in values already mixed together.
        :return: A list representing the input shape specifications.
            By default a value of "None" is returned, indicating that the
            value is indicated in the network builder configuration
            directly, or is determined by that config's defaults.

        The input and/or output shapes specification can each take one of
        a few forms:

                1.  A single list that describes a single shape
                    for a single terminal to be used for all tasks.
                    Like this:  [ 128, 128, 1 ]

                2.  A list of lists that describes a different shape
                    for each single-terminal task. Length of the outer
                    list must equal 'num_tasks' in the config for this
                    to be valid. Like this for num_tasks = 3:
                        [ [ 56, 56, 1 ], [ 23, 23, 1 ], [ 4096, 1 ] ]

                    Note that semantically, this *could* describe a
                    common multi-terminal spec for each task when all
                    tasks terminals are the same. Unfortunately this
                    case is indistinguishable from the case described
                    above and any multi-terminal task must use a fully-
                    specified list described in method (3) below,
                    repeats or no.

                3.  A list of lists of lists that describes a different
                    shape for each terminal of a multi-terminal task.
                    Length of the outer list must equal 'num_tasks' in
                    the config for this to be valid.

                    The outer-most list has one entry per task.
                    The middle-most list has one entry per task-terminal,
                    even if any given task only has a single terminal.
                    The inner-most list has one entry per shape dimension
                    for the task-terminal.

                    Like this:  (1st task - 1 terminal,
                                 2nd task - 2 terminals,
                                 3rd task - 3 terminals)
                        [   [ [ 4096, 1 ] ],
                            [ [ 56, 56, 1 ], [ 23, 23, 1 ] ],
                            [ [ 256, 256, 1 ], [ 56, 56, 1 ], [ 18, 1 ] ]
                        ]

        Specifically for the omniglot domain, the num_tasks from the config
        informs how many tasks are necessary to construct. For this domain, we
        assume a single input terminal and single output terminal per task.
        The (square) image_size and num_channels are used for the shape
        information for the inputs. The language lists inform the shape of
        the outputs for each task.

        This method translates some domain-specific configuration information
        into generalized specifications for the inputs and outputs of the
        network.  The information created here gets sent to the service
        to be digested by the network constructor.

        While it is conceivable that what gets specified here could be done
        statically in the builder config file, that, however, can be a bit
        cumbersome, and the programmatic interpretation of a few domain config
        parameters tends to have fewer errors.
        """

        # Assuming that the service side can duplicate the single
        # input specified here for all tasks.
        image_size = domain_specific_dict['image_size']

        # Use Form (1) above for the input shape specification.
        # However many tasks we have, they all have the same number of input
        # terminals (one) and each terminal has the same shape.
        input_shapes = [image_size, image_size, 1]

        return input_shapes


    def determine_output_shapes(self, domain_specific_dict):
        """
        Called by the SessionServer.

        :param domain_specific_dict: The assembled domain-specific configuration
            dictionary, with defaults and read-in values already mixed together.
        :return: A list representing the output shape specifications.
            By default a value of "None" is returned, indicating that the
            value is indicated in the network builder configuration
            directly, or is determined by that config's defaults.

        The input and/or output shapes specification can each take one of
        a few forms:

                1.  A single list that describes a single shape
                    for a single terminal to be used for all tasks.
                    Like this:  [ 128, 128, 1 ]

                2.  A list of lists that describes a different shape
                    for each single-terminal task. Length of the outer
                    list must equal 'num_tasks' in the config for this
                    to be valid. Like this for num_tasks = 3:
                        [ [ 56, 56, 1 ], [ 23, 23, 1 ], [ 4096, 1 ] ]

                    Note that semantically, this *could* describe a
                    common multi-terminal spec for each task when all
                    tasks terminals are the same. Unfortunately this
                    case is indistinguishable from the case described
                    above and any multi-terminal task must use a fully-
                    specified list described in method (3) below,
                    repeats or no.

                3.  A list of lists of lists that describes a different
                    shape for each terminal of a multi-terminal task.
                    Length of the outer list must equal 'num_tasks' in
                    the config for this to be valid.

                    The outer-most list has one entry per task.
                    The middle-most list has one entry per task-terminal,
                    even if any given task only has a single terminal.
                    The inner-most list has one entry per shape dimension
                    for the task-terminal.

                    Like this:  (1st task - 1 terminal,
                                 2nd task - 2 terminals,
                                 3rd task - 3 terminals)
                        [   [ [ 4096, 1 ] ],
                            [ [ 56, 56, 1 ], [ 23, 23, 1 ] ],
                            [ [ 256, 256, 1 ], [ 56, 56, 1 ], [ 18, 1 ] ]
                        ]

        This method translates some domain-specific configuration information
        into generalized specifications for the inputs and outputs of the
        network.  The information created here gets sent to the service
        to be digested by the network constructor.

        While it is conceivable that what gets specified here could be done
        statically in the builder config file, that, however, can be a bit
        cumbersome, and the programmatic interpretation of a few domain config
        parameters tends to have fewer errors.
        """
        # Output shape specification
        # Use Form (2) above.
        output_shapes = []
        for alphabet_size in domain_specific_dict['alphabet_sizes']:
            output_shape = [alphabet_size]
            output_shapes.append(output_shape)
        return output_shapes
